services:
  backend:
    image: vaxms-backend
    container_name: vaxms-backend-1
    build:
      context: ./vaxms-server
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    env_file:
      - ./vaxms-server/src/main/resources/.env
#    depends_on:
#      - mysql
    networks:
      - app-network

  frontend:
    image: vaxms-frontend
    container_name: vaxms-frontend-1
    build:
      context: ./client-fe
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - app-network

#  mysql:
#    image: mysql:8.0
#    container_name: vaxms-db
#    restart: always
#    environment:
#      MYSQL_DATABASE: vaxms
#      MYSQL_ROOT_PASSWORD: ""
#      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql-data:/var/lib/mysql
#    networks:
#      - app-network

networks:
  app-network:
    driver: bridge

#volumes:
#  mysql-data: