spring:
    application:
        name: vaxms-server

    # Default profile Config
#    profiles:
#        active: dev

    # Database Config
    datasource:
        url: jdbc:postgresql://localhost:5432/vaxms_db
        username: ${LOCAL_POSTGRES_USERNAME}
        password: ${LOCAL_POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver

    # JPA/Hibernate Config
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        database-platform: org.hibernate.dialect.PostgreSQLDialect

    # Mail Config
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_SMTP_USERNAME}
        password: ${MAIL_SMTP_PASSWORD}
        properties:
          mail:
              smtp:
                  auth: true
                  starttls:
                      enable: true
#              debug: true
#              transport:
#                  protocol: smtp

#    data:
#      redis:
#          host: localhost
#          port: 6379
#          password:
#
#
#    rabbitmq:
#        host: localhost
#        port: 5672
#        username: guest
#        password: guest


# JWT Config
jwt:
    secret:  6b8d9e0b7efbb1cb476a1f1b4d3cd5b4a72ecfdfc934d6e889a5b98a781f1234
    expiration: 86400000 # 1 day

# Server Config
#server:
#    port: 8080

# Logging Config
logging:
    level:
        root: info
        com.app.vaxms_server: debug
    file:
        name: logs/vaxms-server.log

# Swagger Config (Optional)
springdoc:
    api-docs:
        path: /v3/api-docs
        enabled: true
    swagger-ui:
        path: /swagger-ui.html
        operations-sorter: alpha
        enabled: true

url:
    frontend: http://localhost:3000

cloudinary:
    cloud-name: dhe0ysmoy
    api-key: 875921558241419
    api-secret: drsU20BRAs03UlD0JWRc5dHwKcg