spring:
  config:
    activate:
      on-profile: dev

  # Ghi đè cấu hình datasource cho môi trường dev (PostgreSQL)
  datasource:
    url: ${DEV_URL}
    username: ${DEV_USERNAME}
    password: ${DEV_PASSWORD}

  # Ghi đè cấu hình JPA
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true

  # Ghi đè cấu hình email (dùng email test)
  mail:
    username: ${DEV_MAIL_USERNAME}
    password: ${DEV_MAIL_PASSWORD}

# Ghi đè cấu hình logging
logging:
  level:
    root: DEBUG
    com.app.vaxms_server: DEBUG