spring:
    application:
        name: vaxms-server

    # Default profile Config
#    profiles:
#        active: dev

    web:
      resources:
          add-mappings: true
    main:
        lazy-initialization: true


    # Database Config
    datasource:
        url: jdbc:mysql://localhost:3306/vaxms
        username: ${LOCAL_MYSQL_USERNAME}
        password: ${LOCAL_MYSQL_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:postgresql://localhost:5432/vaxms
#        username: ${LOCAL_POSTGRES_USERNAME}
#        password: ${LOCAL_POSTGRES_PASSWORD}
#        driver-class-name: org.postgresql.Driver

    # JPA/Hibernate Config
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                id:
                    new_generator_mappings: false
                dialect: org.hibernate.dialect.MySQLDialect
#        database-platform: org.hibernate.dialect.MySQLDialect
#                dialect: org.hibernate.dialect.PostgreSQLDialect
#        database-platform: org.hibernate.dialect.PostgreSQLDialect

    # Mail Config
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_SMTP_USERNAME}
        password: ${MAIL_SMTP_PASSWORD}
        properties:
          mail:
              smtp:
                  auth: true
                  starttls:
                      enable: true
#              debug: true
#              transport:
#                  protocol: smtp

#    data:
#      redis:
#          host: localhost
#          port: 6379
#          password:
#
#
#    rabbitmq:
#        host: localhost
#        port: 5672
#        username: guest
#        password: guest


# JWT Config
jwt:
    secret:  a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3h4i5j6k7l8m9n0o1p2q3r4s5t6u7v8w9x0y1z2
    expiration: 604800000 # 7 day

# Server Config
#server:
#    port: 8080

# Logging Config
logging:
    level:
        root: info
        com.app.vaxms_server: debug
    file:
        name: logs/vaxms-server.log

# Swagger Config (Optional)
springdoc:
    api-docs:
        path: /v3/api-docs
        enabled: true
    swagger-ui:
        path: /swagger-ui.html
        operations-sorter: alpha
        enabled: true

url:
    frontend: http://localhost:3000

cloudinary:
    cloud-name: dhe0ysmoy
    api-key: 875921558241419
    api-secret: drsU20BRAs03UlD0JWRc5dHwKcg