spring:
    application:
        name: vaxms-server

    # Default profile Config
#    profiles:
#        active: dev

    # Database Config
    datasource:
        url: jdbc:postgresql://localhost:5432/vaxms_db
        username: ${LOCAL_POSTGRES_USERNAME}
        password: ${LOCAL_POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver

    # JPA/Hibernate Config
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        database-platform: org.hibernate.dialect.PostgreSQLDialect

    # Mail Config
    mail:
        host: smtp.gmail.com
        port: 587
        username:
        password:
        properties:
          mail:
              smtp:
                  auth: true
                  starttls:
                      enable: true

# JWT Config
jwt:
    secret:
    expiration:

# Server Config
server:
    port: 8080
    servlet:
        context-path: /api

# Logging Config
logging:
    level:
        root: info
        com.vaxms: debug
    file:
        name: logs/vaxms-server.log

# Swagger Config (Optional)
springdoc:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui.html
        operations-sorter: alpha
